name: ajustage
version: 0.1.0.0
github: "confucius40/ajustage"
license: GPL-3.0-or-later
author: "confucius40"
copyright: "2026 confucius40"
description: A minimal, programmable text editor written in Haskell.

extra-source-files:
  - README.md

dependencies:
  - base >= 4.18 && < 5
  - text
  - bytestring
  - containers
  - vector

library:
  source-dirs: src

executables:
  ajustage:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wextra
      - -O2
    dependencies:
      - ajustage

# tests:
#   ajustage-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -Wall
#       - -Wextra
#     dependencies:
#       - ajustage
#       - hspec
